name: geoflutterfire
description: GeoFlutterFire is an open-source library that allows you to store and query firestore documents based on their geographic location.
version: 3.1.0
homepage: https://github.com/DarshanGowda0/GeoFlutterFire

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^5.0.2
  rxdart: ^0.27.7
  flutter_lints: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
